services:
  opensearch-cluster-base:
    image: opensearchproject/opensearch:latest
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
#      - node.name=opensearch # Name the node that will run in this container
#      - discovery.seed_hosts=opensearch,opensearch2 # Nodes to look for when discovering the cluster
#      - cluster.initial_cluster_manager_nodes=opensearch,opensearch2 # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
