version: '3'
services:
  app-wiremock:
    image: wiremock/wiremock:3.4.2
    ports:
      - "8080:8080"
    volumes:
      - ./volumes/wm-marketplace/mappings:/home/wiremock/mappings
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
