services:
  keycloak-base:
    image: quay.io/keycloak/keycloak:26.1.0
    #    ports:
    #      - "8081:8080"
    volumes:
      - ./volumes/keycloak/import:/opt/keycloak/data/import
    #      - ./keycloak/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
    #      - ./keycloak/certs/keycloak.jks:/etc/x509/https/keystore  # Mount your Keycloak keystore
    environment:
      KEYCLOAK_USER: otus
      KEYCLOAK_PASSWORD: otus
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: "/tmp/realm-export.json"
      KC_HEALTH_ENABLED: "true"
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'HEAD /health/ready HTTP/1.1\r\nHost: localhost:9000\r\nConnection: close\r\n\r\n' >&3;cat <&3" ]
      interval: 10s
      timeout: 5s
      retries: 15
    command:
      - start-dev
      - --import-realm
      - --hostname-strict
      - "false"
      - --hostname
      - "http://localhost:8080/"
      - --proxy-headers
      - forwarded
      - --hostname-backchannel-dynamic
      - "true"